import Head from 'next/head'
import Image from 'next/image'
import About from '../src/components/About'
import Header from '../src/components/header'
import Projects from '../src/components/Projects'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        <Header></Header>
        <div className={styles.content}>
        <About></About>
        <Projects></Projects>
        </div>
      </div>
    </div>
  )
}
